name=PH8
version=0.1.0
author=2011-2024 Symisc Systems, 2026 Viacheslav Logunov
maintainer=Viacheslav Logunov <vvb333007@gmail.com>
license=GPL
sentence=PH8 for ESP32
paragraph=Embeddable PHP compiler and a virtual machine (fork of the PH7 Engine)
category=other
url=https://github.com/vvb333007/PH8
architectures=esp32
includes=ph7.h
