name=embedded-php-compiler-vm
version=0.0.1
author=2011-2014 Symisc Systems, 2026 Viacheslav Logunov
maintainer=Viacheslav Logunov <vvb333007@gmail.com>
license=GPL
sentence=PH7 for ESP32
paragraph=Embeddable PHP compiler and a virtual machine (fork of the PH7 Engine)
category=other
url=https://github.com/vvb333007/embedded-php-compiler-vm
architectures=esp32
includes=ph7.h
