<?
/*
 * Complex expressions for function arguments default values.
 *
 * While the standard PHP engine would allow simple scalar values for function
 * arguments default values,PH7 goes further and let you use any complex expressions
 * including function calls,math or string expressions and so on as a default values
 * for your function arguments.
 *
 * Refer to: http://ph7.symisc.net/features.html#complex for a full discussion on this
 * extension.
 */
 /*
  * The $name parameter takes as it's default value a complex expression which is the concatenation
  * of the string 'PH7' and a random string of length 4 bytes generated by the built-in rand_str() function.
  * The default value for the $age parameter is a constant math expression. If you run this example using
  * the standard PHP engine,you will get a fatal error while under PH7 this example would run perfectly.
  */
function test($name = 'PH7 '.rand_str(4),$age = 10 * 2 + 5)
{
 echo "Name = $name\n";
 echo "Age = $age\n";
}
/* Call without arguments */

test(); /* You should see: name = PH7 rscd age = 25 */
/* Call with a single argument */

test('Me'); /* You should see: name = Me age = 25 */

?>