/*
** Compile (gcc) and run this standalone program in order to generate code that
** implements a function that will translate alphabetic identifiers into
** parser token codes.
*/
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

//#include "../src/ph7int.h"


/* Parameter to the hash function.
 *
 */
#define HASH_OP ^
#define HASH_CC '^'
#define HASH_C0 3     
#define HASH_C1 2467
#define HASH_C2 3041



/*
** A header comment placed at the beginning of generated code.
*/
static const char zHdr[] = 
  "/* This file contains automatically generated code\n"
  " *\n"
  " * The code in this file has been automatically generated by\n"
  " *\n"
  " *   ../tools/mkkeywordhash.c (derived from SQLite source tree)\n"
  " */\n"
;

/*
** All the keywords of the PHP language are stored in a hash
** table composed of instances of the following structure.
*/
typedef struct Keyword Keyword;
struct Keyword {
  char *zName;         /* The keyword name */
  char *zTokenType;    /* Token value for this keyword */
  int mask;            /* Code this keyword if non-zero */
  int priority;        /* Put higher priorities earlier in the hash chain */
  
  int id;              /* Unique ID for this record */
  int hash;            /* Hash on the keyword */
  int offset;          /* Offset to start of name string */
  int len;             /* Length of this keyword, not counting final \000 */
  int prefix;          /* Number of characters in prefix */
  int longestSuffix;   /* Longest suffix that is a prefix on another word */
  int iNext;           /* Index in aKeywordTable[] of next with same hash */
  int substrId;        /* Id to another keyword this keyword is embedded in */
  int substrOffset;    /* Offset into substrId for start of this keyword */
  char zOrigName[20];  /* Original keyword name before processing */
};

/*
** These are the keywords
*/
static Keyword aKeywordTable[] = {
  { "extends",         "PH7_TKWRD_EXTENDS", 1, 9 },
  { "endswitch",       "PH7_TKWRD_ENDSWITCH", 1, 0 },
  { "switch",          "PH7_TKWRD_SWITCH", 1, 0 },
  { "print",           "PH7_TKWRD_PRINT", 1, 10 },
  { "int",             "PH7_TKWRD_INT", 1, 10 },
  { "interface",       "PH7_TKWRD_INTERFACE", 1, 0 },
  { "require",         "PH7_TKWRD_REQUIRE", 1, 0 },
  { "require_once",    "PH7_TKWRD_REQONCE", 1, 10 },
  { "seq",             "PH7_TKWRD_SEQ", 1, 0 },
  { "enddec",          "PH7_TKWRD_ENDDEC", 1, 0 },
  { "declare",         "PH7_TKWRD_DECLARE", 1, 0 },
  { "return",          "PH7_TKWRD_RETURN", 1, 0 },
  { "namespace",       "PH7_TKWRD_NAMESPACE", 1, 0 },
  { "echo",            "PH7_TKWRD_ECHO", 1, 0 },
  { "object",          "PH7_TKWRD_OBJECT", 1, 10 },
  { "throw",           "PH7_TKWRD_THROW", 1, 10 },
  { "bool",            "PH7_TKWRD_BOOL", 1, 0 },
  { "and",             "PH7_TKWRD_AND", 1, 0 },
  { "default",         "PH7_TKWRD_DEFAULT", 1, 0 },
  { "try",             "PH7_TKWRD_TRY", 1, 0 },
  { "case",            "PH7_TKWRD_CASE", 1, 0 },
  { "self",            "PH7_TKWRD_SELF", 1, 10 },
  { "final",           "PH7_TKWRD_FINAL", 1, 0 },
  { "list",            "PH7_TKWRD_LIST", 1, 0 },
  { "static",          "PH7_TKWRD_STATIC", 1, 10 },
  { "clone",           "PH7_TKWRD_CLONE", 1, 0 },
  { "never",           "PH7_TKWRD_NEVER", 1, 0 },
  { "enum",            "PH7_TKWRD_ENUM", 1, 4 },
  { "mixed",           "PH7_TKWRD_MIXED", 1, 0 },
  { "sne",             "PH7_TKWRD_SNE", 1, 0 },
  { "new",             "PH7_TKWRD_NEW", 1, 0 },
  { "const",           "PH7_TKWRD_CONST", 1, 0 },
  { "string",          "PH7_TKWRD_STRING", 1, 0 },
  { "global",          "PH7_TKWRD_GLOBAL", 1, 0 },
  { "use",             "PH7_TKWRD_USE", 1, 0 },
  { "elif",            "PH7_TKWRD_ELIF", 1, 0 },
  { "else",            "PH7_TKWRD_ELSE", 1, 0 },
  { "if",              "PH7_TKWRD_IF", 1, 10 },
  { "float",           "PH7_TKWRD_FLOAT", 1, 0 },
  { "var",             "PH7_TKWRD_VAR", 1, 0 },
  { "array",           "PH7_TKWRD_ARRAY", 1, 0 },
  { "void",            "PH7_TKWRD_VOID", 1, 0 },
  { "die",             "PH7_TKWRD_DIE", 1, 0 },
  { "abstract",        "PH7_TKWRD_ABSTRACT", 1, 10 },
  { "class",           "PH7_TKWRD_CLASS", 1, 0 },
  { "as",              "PH7_TKWRD_AS", 1, 5 },
  { "continue",        "PH7_TKWRD_CONTINUE", 1, 0 },
  { "endif",           "PH7_TKWRD_ENDIF", 1, 0 },
  { "function",        "PH7_TKWRD_FUNCTION", 1, 0 },
  { "endwhile",        "PH7_TKWRD_ENDWHILE", 1, 0 },
  { "while",           "PH7_TKWRD_WHILE", 1, 0 },
  { "eval",            "PH7_TKWRD_EVAL", 1, 0 },
  { "do",              "PH7_TKWRD_DO", 1, 0 },
  { "exit",            "PH7_TKWRD_EXIT", 1, 0 },
  { "goto",            "PH7_TKWRD_GOTO", 1, 0 },
  { "implements",      "PH7_TKWRD_IMPLEMENTS", 1, 0 },
  { "include",         "PH7_TKWRD_INCLUDE", 1, 0 },
  { "include_once",    "PH7_TKWRD_INCONCE", 1, 0 },
  { "empty",           "PH7_TKWRD_EMPTY", 1, 0 },
  { "instanceof",      "PH7_TKWRD_INSTANCEOF", 1, 0 },
  { "for",             "PH7_TKWRD_FOR", 1, 0 },
  { "or",              "PH7_TKWRD_OR", 1, 0 },
  { "endfor",          "PH7_TKWRD_ENDFOR", 1, 8 },
  { "endforeach",      "PH7_TKWRD_END4EACH", 1, 0 },
  { "foreach",         "PH7_TKWRD_FOREACH", 1, 0 },
  { "isset",           "PH7_TKWRD_ISSET", 1, 0 },
  { "parent",          "PH7_TKWRD_PARENT", 1, 0 },
  { "private",         "PH7_TKWRD_PRIVATE", 1, 10 },
  { "protected",       "PH7_TKWRD_PROTECTED", 1, 0 },
  { "public",          "PH7_TKWRD_PUBLIC", 1, 0 },
  { "catch",           "PH7_TKWRD_CATCH", 1, 0 },
  { "unset",           "PH7_TKWRD_UNSET", 1, 0 },
  { "xor",             "PH7_TKWRD_XOR", 1, 0 },
  { "break",           "PH7_TKWRD_BREAK", 1, 6 },
  { "callable",        "PH7_TKWRD_CALLABLE", 1, 6 },
};

/* Number of keywords */
static int nKeyword = (sizeof(aKeywordTable)/sizeof(aKeywordTable[0]));

#define charMap(X)   (X)

/*
** Comparision function for two Keyword records
*/
static int keywordCompare1(const void *a, const void *b){
  const Keyword *pA = (Keyword*)a;
  const Keyword *pB = (Keyword*)b;
  int n = pA->len - pB->len;
  if( n==0 ){
    n = strcmp(pA->zName, pB->zName);
  }
//  if (n == 0)
//    printf("%s == %s\r\n",pA->zName, pB->zName);
  assert( n!=0 );
  return n;
}
static int keywordCompare2(const void *a, const void *b){
  const Keyword *pA = (Keyword*)a;
  const Keyword *pB = (Keyword*)b;
  int n = pB->longestSuffix - pA->longestSuffix;
  if( n==0 ){
    n = strcmp(pA->zName, pB->zName);
  }
  assert( n!=0 );
  return n;
}
static int keywordCompare3(const void *a, const void *b){
  const Keyword *pA = (Keyword*)a;
  const Keyword *pB = (Keyword*)b;
  int n = pA->offset - pB->offset;
  if( n==0 ) n = pB->id - pA->id;
  assert( n!=0 );
  return n;
}

/*
** Return a KeywordTable entry with the given id
*/
static Keyword *findById(int id){
  int i;
  for(i=0; i<nKeyword; i++){
    if( aKeywordTable[i].id==id ) break;
  }
  return &aKeywordTable[i];
}

/*
** If aKeyword[*pFrom-1].iNext has a higher priority that aKeyword[*pFrom-1]
** itself, then swap them.
*/
static void reorder(int *pFrom){
  int i = *pFrom - 1;
  int j;
  if( i<0 ) return;
  j = aKeywordTable[i].iNext;
  if( j==0 ) return;
  j--;
  if( aKeywordTable[i].priority >= aKeywordTable[j].priority ) return;
  aKeywordTable[i].iNext = aKeywordTable[j].iNext;
  aKeywordTable[j].iNext = i+1;
  *pFrom = j+1;
  reorder(&aKeywordTable[i].iNext);
}


/*
** This routine does the work.  The generated code is printed on standard
** output.
*/
int main(int argc, char **argv){
  int i, j, k, h;
  int bestSize, bestCount;
  int count;
  int nChar;
  int totalLen = 0;
  int aKWHash[1000];  /* 1000 is much bigger than nKeyword */
  char zKWText[2000];

  /* Remove entries from the list of keywords that have mask==0 */
  for(i=j=0; i<nKeyword; i++){
    if( aKeywordTable[i].mask==0 ) continue;
    if( j<i ){
      aKeywordTable[j] = aKeywordTable[i];
    }
    j++;
  }
  nKeyword = j;

  /* Fill in the lengths of strings and hashes for all entries. */
  for(i=0; i<nKeyword; i++){
    Keyword *p = &aKeywordTable[i];
    p->len = (int)strlen(p->zName);
    assert( p->len<sizeof(p->zOrigName) );
    memcpy(p->zOrigName, p->zName, p->len+1);
    totalLen += p->len;
    p->hash = (charMap(p->zName[0])*HASH_C0) HASH_OP
              (charMap(p->zName[p->len-1])*HASH_C1) HASH_OP
              (p->len*HASH_C2);
    p->id = i+1;
  }

  /* Sort the table from shortest to longest keyword */
  qsort(aKeywordTable, nKeyword, sizeof(aKeywordTable[0]), keywordCompare1);

  /* Look for short keywords embedded in longer keywords */
  for(i=nKeyword-2; i>=0; i--){
    Keyword *p = &aKeywordTable[i];
    for(j=nKeyword-1; j>i && p->substrId==0; j--){
      Keyword *pOther = &aKeywordTable[j];
      if( pOther->substrId ) continue;
      if( pOther->len<=p->len ) continue;
      for(k=0; k<=pOther->len-p->len; k++){
        if( memcmp(p->zName, &pOther->zName[k], p->len)==0 ){
          p->substrId = pOther->id;
          p->substrOffset = k;
          break;
        }
      }
    }
  }

  /* Compute the longestSuffix value for every word */
  for(i=0; i<nKeyword; i++){
    Keyword *p = &aKeywordTable[i];
    if( p->substrId ) continue;
    for(j=0; j<nKeyword; j++){
      Keyword *pOther;
      if( j==i ) continue;
      pOther = &aKeywordTable[j];
      if( pOther->substrId ) continue;
      for(k=p->longestSuffix+1; k<p->len && k<pOther->len; k++){
        if( memcmp(&p->zName[p->len-k], pOther->zName, k)==0 ){
          p->longestSuffix = k;
        }
      }
    }
  }

  /* Sort the table into reverse order by length */
  qsort(aKeywordTable, nKeyword, sizeof(aKeywordTable[0]), keywordCompare2);

  /* Fill in the offset for all entries */
  nChar = 0;
  for(i=0; i<nKeyword; i++){
    Keyword *p = &aKeywordTable[i];
    if( p->offset>0 || p->substrId ) continue;
    p->offset = nChar;
    nChar += p->len;
    for(k=p->len-1; k>=1; k--){
      for(j=i+1; j<nKeyword; j++){
        Keyword *pOther = &aKeywordTable[j];
        if( pOther->offset>0 || pOther->substrId ) continue;
        if( pOther->len<=k ) continue;
        if( memcmp(&p->zName[p->len-k], pOther->zName, k)==0 ){
          p = pOther;
          p->offset = nChar - k;
          nChar = p->offset + p->len;
          p->zName += k;
          p->len -= k;
          p->prefix = k;
          j = i;
          k = p->len;
        }
      }
    }
  }
  for(i=0; i<nKeyword; i++){
    Keyword *p = &aKeywordTable[i];
    if( p->substrId ){
      p->offset = findById(p->substrId)->offset + p->substrOffset;
    }
  }

  /* Sort the table by offset */
  qsort(aKeywordTable, nKeyword, sizeof(aKeywordTable[0]), keywordCompare3);

  /* Figure out how big to make the hash table in order to minimize the
  ** number of collisions */
  bestSize = nKeyword;
  bestCount = nKeyword*nKeyword;
  for(i=nKeyword/2; i<=2*nKeyword; i++){
    if( i<=0 ) continue;
    for(j=0; j<i; j++) aKWHash[j] = 0;
    for(j=0; j<nKeyword; j++){
      h = aKeywordTable[j].hash % i;
      aKWHash[h] *= 2;
      aKWHash[h]++;
    }
    for(j=count=0; j<i; j++) count += aKWHash[j];
    if( count<bestCount ){
      bestCount = count;
      bestSize = i;
    }
  }

  /* Compute the hash */
  for(i=0; i<bestSize; i++) aKWHash[i] = 0;
  for(i=0; i<nKeyword; i++){
    h = aKeywordTable[i].hash % bestSize;
    aKeywordTable[i].iNext = aKWHash[h];
    aKWHash[h] = i+1;
    reorder(&aKWHash[h]);
  }

  /* Begin generating code */
  printf("%s", zHdr);

  printf("static sxu32 KeywordCode(const char *z, int n) {\n");

  printf("/* Hash score: %d\n", bestCount);

  printf(" * zText[] encodes %d bytes of keyword text in %d bytes */\n", totalLen + nKeyword, nChar+1 );
  for(i=j=k=0; i<nKeyword; i++){
    Keyword *p = &aKeywordTable[i];
    if( p->substrId ) continue;
    memcpy(&zKWText[k], p->zName, p->len);
    k += p->len;
    if( j+p->len>70 ){
      printf("%*s */\n", 74-j, "");
      j = 0;
    }
    if( j==0 ){
      printf("/*   ");
      j = 8;
    }
    printf("%s", p->zName);
    j += p->len;
  }
  if( j>0 ){
    printf("%*s */\n", 74-j, "");
  }
  printf("static const char zText[%d] = {\n", nChar);
  zKWText[nChar] = 0;
  for(i=j=0; i<k; i++){
    if( j==0 ){
      printf("  ");
    }
    if( zKWText[i]==0 ){
      printf("0");
    }else{
      printf("'%c',", zKWText[i]);
    }
    j += 4;
    if( j>68 ){
      printf("\n");
      j = 0;
    }
  }
  if( j>0 ) printf("\n");
  printf("};\n");

  printf("/* aHash[i] is the hash value for the i-th keyword */\n");
  printf("static const unsigned char aHash[%d] = {\n", bestSize);
  for(i=j=0; i<bestSize; i++){
    if( j==0 ) printf("  ");
    printf(" %3d,", aKWHash[i]);
    j++;
    if( j>12 ){
      printf("\n");
      j = 0;         
    }
  }
  printf("%s};\n", j==0 ? "" : "\n");    

  printf("/* aNext[] forms the hash collision chain.  If aHash[i]==0\n");
  printf("** then the i-th keyword has no more hash collisions.  Otherwise,\n");
  printf("** the next keyword with the same hash is aHash[i]-1. */\n");
  printf("static const unsigned char aNext[%d] = {\n", nKeyword+1);
  for(i=j=0; i<nKeyword; i++){
    if( j==0 ) printf("  ");
    printf(" %3d,", aKeywordTable[i].iNext);
    j++;
    if( j>12 ){
      printf("\n");
      j = 0;
    }
  }
  printf("%s};\n", j==0 ? "" : "\n");    

  printf("/* aLen[i] is the length (in bytes) of the i-th keyword */\n");
  printf("static const unsigned char aLen[%d] = {\n", nKeyword+1);
  for(i=j=0; i<nKeyword; i++){
    if( j==0 ) printf("  ");
    printf(" %3d,", aKeywordTable[i].len+aKeywordTable[i].prefix);
    j++;
    if( j>12 ){
      printf("\n");
      j = 0;
    }
  }
  printf("%s};\n", j==0 ? "" : "\n");    

  printf("/* aOffset[i] is the index into zText[] of the start of\n");
  printf("** the text for the i-th keyword. */\n");
  printf("static const unsigned short int aOffset[%d] = {\n", nKeyword+1);
  for(i=j=0; i<nKeyword; i++){
    if( j==0 ) printf("  ");
    printf(" %3d,", aKeywordTable[i].offset);
    j++;
    if( j>12 ){
      printf("\n");
      j = 0;
    }
  }
  printf("%s};\n", j==0 ? "" : "\n");

  printf("/* aCode[i] is the parser symbol code for the i-th keyword */\n");
  printf("static const sxu32 aCode[%d] = {\n", nKeyword+1);
  for(i=j=0; i<nKeyword; i++){
    char *zToken = aKeywordTable[i].zTokenType;
    if( j==0 ) printf("  ");
    printf("%s,%*s", zToken, (int)(20-strlen(zToken)), "");
    j++;
    if( j>=5 ){
      printf("\n");
      j = 0;
    }
  }
  printf("%s};\n", j==0 ? "" : "\n");
  printf("/* Hash table decoded ( --> collision chain):\n");

  for(i=0; i<bestSize; i++){
    j = aKWHash[i];
    if (j) {
      printf(" * %3d:", i);
      if (aKeywordTable[j-1].iNext)
        printf("    --> ");
      while( j ){
        printf(" %s    ", aKeywordTable[j-1].zOrigName);
        j = aKeywordTable[j-1].iNext;
      }
      printf("\n");
    }
  }
  printf( "*/\n"
          "\n"
          "  int h, i;\n"
          "\n"
          "/* PH7 has no keywords consisting of a single character */\n"
          "  if (n < 2)\n    return PH7_TK_ID;\n"
          "/* Calculate hash */\n"
          "  h = ( ((int)(z[0])*%d) %c ((int)(z[n-1])*%d) %c n*%d) %% %d;\n",
          HASH_C0,
          HASH_CC,

          HASH_C1,
          HASH_CC,

          HASH_C2,

          bestSize);

  printf("\n"
         "/* Run through collision chain and find our entry */\n"
         "  for (i = ((int)aHash[h]) - 1; i >= 0; i = ((int)aNext[i]) - 1) {\n"
         "    if ((int)aLen[i] == n &&\n"
         "        zText[aOffset[i]] == z[0] &&\n"
         "        SyMemcmp(&zText[aOffset[i]], z, n) == 0) {\n"
         "\n"
         "      return aCode[i];\n"
         "    }\n"
         "  }\n"
         " /* Not a built-in keyword. */\n"
         "  return PH7_TK_ID;\n"
         "}\n");


  return 0;
}
