/* This file contains automatically generated code
 *
 * The code in this file has been automatically generated by
 *
 *   ../tools/mkkeywordhash.c (modified from SQLite source tree)
 */
static sxu32 KeywordCode(const char *z, int n) {
/* Hash score: 81
 * zText[] encodes 479 bytes of keyword text in 306 bytes */
/*   extendswitchenddeclarequire_oncelselfinalistaticaseqprint          */
/*   erfacechobjecthrowclonevereturnamespacelifloatryconstringlobal     */
/*   snewusendifunctionvarrayabstractandefaultboolclasscontinue         */
/*   ndwhilenumixedievaldoexitgotoimplementsinclude_oncempty            */
/*   instanceofissetparentprivatendforeachprotectedpublicatchunset      */
/*   voidxorbreak                                                       */
static const char zText[305] = {
  'e','x','t','e','n','d','s','w','i','t','c','h','e','n','d','d','e','c',
  'l','a','r','e','q','u','i','r','e','_','o','n','c','e','l','s','e','l',
  'f','i','n','a','l','i','s','t','a','t','i','c','a','s','e','q','p','r',
  'i','n','t','e','r','f','a','c','e','c','h','o','b','j','e','c','t','h',
  'r','o','w','c','l','o','n','e','v','e','r','e','t','u','r','n','a','m',
  'e','s','p','a','c','e','l','i','f','l','o','a','t','r','y','c','o','n',
  's','t','r','i','n','g','l','o','b','a','l','s','n','e','w','u','s','e',
  'n','d','i','f','u','n','c','t','i','o','n','v','a','r','r','a','y','a',
  'b','s','t','r','a','c','t','a','n','d','e','f','a','u','l','t','b','o',
  'o','l','c','l','a','s','s','c','o','n','t','i','n','u','e','n','d','w',
  'h','i','l','e','n','u','m','i','x','e','d','i','e','v','a','l','d','o',
  'e','x','i','t','g','o','t','o','i','m','p','l','e','m','e','n','t','s',
  'i','n','c','l','u','d','e','_','o','n','c','e','m','p','t','y','i','n',
  's','t','a','n','c','e','o','f','i','s','s','e','t','p','a','r','e','n',
  't','p','r','i','v','a','t','e','n','d','f','o','r','e','a','c','h','p',
  'r','o','t','e','c','t','e','d','p','u','b','l','i','c','a','t','c','h',
  'u','n','s','e','t','v','o','i','d','x','o','r','b','r','e','a','k',
};
/* aHash[i] is the hash value for the i-th keyword */
static const unsigned char aHash[147] = {
    37,   0,   0,  51,   0,   0,  73,   0,   0,   0,  49,   1,  36,
     0,  57,   0,   0,   0,   0,   0,  23,   0,   0,  47,  24,   0,
    46,  68,  74,  39,  58,  65,  45,   0,  71,  48,   0,  15,   0,
     0,   3,   0,  38,   0,   0,  30,   0,   0,  13,   0,   8,   0,
     0,   0,   0,  53,   0,  63,   0,   0,   0,   0,   6,   0,  10,
     0,   0,  66,  20,   0,  12,   0,  70,  52,   0,   0,   0,   0,
     0,  69,   0,  60,  18,   0,   0,   0,   0,   0,  22,  55,  26,
     0,  16,   0,  21,  28,  43,   0,   0,   0,   9,  61,   0,  44,
    72,  34,   0,   0,   0,   0,  62,  11,   0,   0,  19,   0,   7,
     0,   0,   0,   0,   0,   5,   0,  32,   2,   0,   0,  59,  41,
     0,   0,   0,  33,  35,  31,  17,  56,   0,   0,   0,  42,  25,
     0,   4,   0,  50,
};
/* aNext[] forms the hash collision chain.  If aHash[i]==0
** then the i-th keyword has no more hash collisions.  Otherwise,
** the next keyword with the same hash is aHash[i]-1. */
static const unsigned char aNext[75] = {
     0,   0,   0,   0,   0,   0,   0,   0,  67,   0,   0,   0,   0,
     0,   0,   0,  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,
     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  14,  29,
     0,   0,  40,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
     0,   0,   0,   0,  27,   0,  54,   0,   0,
};
/* aLen[i] is the length (in bytes) of the i-th keyword */
static const unsigned char aLen[75] = {
     7,   9,   6,   6,   7,  12,   7,   4,   4,   5,   4,   6,   4,
     3,   5,   9,   3,   4,   6,   5,   5,   5,   6,   9,   4,   5,
     3,   5,   6,   6,   3,   3,   3,   5,   2,   8,   3,   5,   8,
     3,   7,   4,   5,   2,   8,   8,   5,   4,   5,   3,   4,   2,
     4,   4,  10,   7,  12,   5,  10,   5,   6,   7,  10,   6,   7,
     3,   2,   9,   6,   5,   5,   4,   3,   5,
};
/* aOffset[i] is the index into zText[] of the start of
** the text for the i-th keyword. */
static const unsigned short int aOffset[75] = {
     0,   3,   6,  12,  15,  20,  20,  31,  33,  36,  40,  42,  47,
    49,  52,  54,  54,  62,  65,  70,  75,  78,  82,  87,  95,  98,
   102, 105, 108, 113, 119, 120, 123, 125, 128, 129, 137, 138, 143,
   151, 153, 160, 164, 166, 169, 176, 179, 183, 186, 190, 192, 196,
   198, 202, 206, 216, 216, 227, 232, 242, 247, 253, 259, 259, 262,
   262, 263, 269, 278, 283, 288, 293, 297, 300,
};
/* aCode[i] is the parser symbol code for the i-th keyword */
static const sxu32 aCode[75] = {
  PH7_TKWRD_EXTENDS,   PH7_TKWRD_ENDSWITCH, PH7_TKWRD_SWITCH,    PH7_TKWRD_ENDDEC,    PH7_TKWRD_DECLARE,   
  PH7_TKWRD_REQONCE,   PH7_TKWRD_REQUIRE,   PH7_TKWRD_ELSE,      PH7_TKWRD_SELF,      PH7_TKWRD_FINAL,     
  PH7_TKWRD_LIST,      PH7_TKWRD_STATIC,    PH7_TKWRD_CASE,      PH7_TKWRD_SEQ,       PH7_TKWRD_PRINT,     
  PH7_TKWRD_INTERFACE, PH7_TKWRD_INT,       PH7_TKWRD_ECHO,      PH7_TKWRD_OBJECT,    PH7_TKWRD_THROW,     
  PH7_TKWRD_CLONE,     PH7_TKWRD_NEVER,     PH7_TKWRD_RETURN,    PH7_TKWRD_NAMESPACE, PH7_TKWRD_ELIF,      
  PH7_TKWRD_FLOAT,     PH7_TKWRD_TRY,       PH7_TKWRD_CONST,     PH7_TKWRD_STRING,    PH7_TKWRD_GLOBAL,    
  PH7_TKWRD_SNE,       PH7_TKWRD_NEW,       PH7_TKWRD_USE,       PH7_TKWRD_ENDIF,     PH7_TKWRD_IF,        
  PH7_TKWRD_FUNCTION,  PH7_TKWRD_VAR,       PH7_TKWRD_ARRAY,     PH7_TKWRD_ABSTRACT,  PH7_TKWRD_AND,       
  PH7_TKWRD_DEFAULT,   PH7_TKWRD_BOOL,      PH7_TKWRD_CLASS,     PH7_TKWRD_AS,        PH7_TKWRD_CONTINUE,  
  PH7_TKWRD_ENDWHILE,  PH7_TKWRD_WHILE,     PH7_TKWRD_ENUM,      PH7_TKWRD_MIXED,     PH7_TKWRD_DIE,       
  PH7_TKWRD_EVAL,      PH7_TKWRD_DO,        PH7_TKWRD_EXIT,      PH7_TKWRD_GOTO,      PH7_TKWRD_IMPLEMENTS,
  PH7_TKWRD_INCLUDE,   PH7_TKWRD_INCONCE,   PH7_TKWRD_EMPTY,     PH7_TKWRD_INSTANCEOF,PH7_TKWRD_ISSET,     
  PH7_TKWRD_PARENT,    PH7_TKWRD_PRIVATE,   PH7_TKWRD_END4EACH,  PH7_TKWRD_ENDFOR,    PH7_TKWRD_FOREACH,   
  PH7_TKWRD_FOR,       PH7_TKWRD_OR,        PH7_TKWRD_PROTECTED, PH7_TKWRD_PUBLIC,    PH7_TKWRD_CATCH,     
  PH7_TKWRD_UNSET,     PH7_TKWRD_VOID,      PH7_TKWRD_XOR,       PH7_TKWRD_BREAK,     
};
/* Hash table decoded:
 *   0: var    
 *   3:    -->  eval     seq    
 *   6: xor    
 *  10: mixed    
 *  11: extends    
 *  12: function    
 *  14: include_once    
 *  20: return    
 *  23: while    
 *  24: namespace    
 *  26: endwhile    
 *  27: protected    
 *  28: break    
 *  29: abstract    
 *  30: empty    
 *  31: foreach    
 *  32: continue    
 *  34: unset    
 *  35: enum    
 *  37: print    
 *  40: switch    
 *  42: array    
 *  45: global    
 *  48: case    
 *  50: else    
 *  55: exit    
 *  57: endforeach    
 *  62: require_once    
 *  64: final    
 *  67: for    
 *  68: throw    
 *  70: static    
 *  72:    -->  catch     try    
 *  73:    -->  do     string    
 *  79: public    
 *  81: isset    
 *  82: echo    
 *  88: never    
 *  89:    -->  implements     and    
 *  90: float    
 *  92: interface    
 *  94: clone    
 *  95: const    
 *  96: class    
 * 100:    -->  self     or    
 * 101: parent    
 * 103: as    
 * 104:    -->  void     goto    
 * 105: endif    
 * 110: private    
 * 111: list    
 * 114: object    
 * 116: require    
 * 122: declare    
 * 124: new    
 * 125: endswitch    
 * 128: instanceof    
 * 129: default    
 * 133: use    
 * 134: if    
 * 135: sne    
 * 136:    -->  int     endfor    
 * 137: include    
 * 141: bool    
 * 142: elif    
 * 144: enddec    
 * 146: die    
*/

  int h, i;
  if (n < 2) return PH7_TK_ID;
  h = (((int)(z[0])*3) ^ ((int)(z[n-1])*2467) ^ n*3041) % 147;


  for (i = ((int)aHash[h]) - 1; i >= 0; i = ((int)aNext[i]) - 1) {
    if ((int)aLen[i] == n &&
        zText[aOffset[i]] == z[0] &&
        SyMemcmp(&zText[aOffset[i]], z, n) == 0) {

      return aCode[i];
    }
  }
 /* Not a built-in keyword. */
  return PH7_TK_ID;
}
